// Generates supabase/seed/001_demo.sql from TypeScript data so the seeded
// framework always passes framework.validateConfig. Deterministic: fixed ids,
// fixed salts, so regenerating produces the same file (the test checks it).
import { scryptSync, createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { framework } from "@wbl/domain";
import { noorahDemoConfig } from "./seed/demo-config";

const out = path.resolve(import.meta.dirname, "../supabase/seed/001_demo.sql");
const q = (s: string | null | undefined) => (s === null || s === undefined ? "null" : `'${s.replace(/'/g, "''")}'`);
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const uuid = (label: string) => { const h = createHash("sha256").update(label).digest("hex"); return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-8${h.slice(17, 20)}-${h.slice(20, 32)}`; };
export function hashPassword(pw: string, salt: string) {
  const key = scryptSync(pw, salt, 32, { N: 16384, r: 8, p: 1 });
  return `scrypt$16384$8$1$${Buffer.from(salt).toString("base64")}$${key.toString("base64")}`;
}

export const DEMO_PASSWORD = "Wbl-demo-2026";
// Base32 TOTP secrets for staff — demo only, so e2e tests can produce codes.
export const DEMO_TOTP = "JBSWY3DPEHPK3PXP";

const A = uuid("tenant:almulhi"), B = uuid("tenant:second");
const cfg = noorahDemoConfig();
const valid = framework.validateConfig(cfg);
if (!valid.ok) throw new Error(`demo config invalid: ${valid.errors.join("; ")}`);
const cfgB = framework.defaultConfig("مؤسسة تجريبية ثانية");

type P = { key: string; name: string; email: string; phone: string; tenant: string; role: string; org?: string; staff: boolean };
const assoc = { albir: uuid("assoc:albir"), aytam: uuid("assoc:aytam"), namaa: uuid("assoc:namaa"), other: uuid("assoc:b-1") };
const supplier = uuid("supplier:sew");
const people: P[] = [
  { key: "admin", name: "نوف السبيعي", email: "admin@almulhi.demo", phone: "+966500100001", tenant: A, role: "system_admin", staff: true },
  { key: "sara", name: "سارة العتيبي", email: "sara@almulhi.demo", phone: "+966500100002", tenant: A, role: "grants_specialist", staff: true },
  { key: "khalid", name: "خالد الشهري", email: "khalid@almulhi.demo", phone: "+966500100003", tenant: A, role: "grants_specialist", staff: true },
  { key: "manager", name: "منيرة القحطاني", email: "manager@almulhi.demo", phone: "+966500100004", tenant: A, role: "grants_manager", staff: true },
  { key: "secretary", name: "فهد الدوسري", email: "secretary@almulhi.demo", phone: "+966500100005", tenant: A, role: "committee_secretary", staff: true },
  { key: "finance", name: "ريم الحربي", email: "finance@almulhi.demo", phone: "+966500100006", tenant: A, role: "finance", staff: true },
  { key: "ceo", name: "عبدالله الملاحي", email: "ceo@almulhi.demo", phone: "+966500100007", tenant: A, role: "executive", staff: true },
  { key: "albir", name: "عبدالرحمن الزهراني", email: "owner@albir.demo", phone: "+966500000147", tenant: A, role: "assoc_owner", org: assoc.albir, staff: false },
  { key: "albir-coord", name: "هند الغامدي", email: "coord@albir.demo", phone: "+966500000148", tenant: A, role: "assoc_coordinator", org: assoc.albir, staff: false },
  { key: "namaa", name: "ماجد المطيري", email: "owner@namaa.demo", phone: "+966500000345", tenant: A, role: "assoc_owner", org: assoc.namaa, staff: false },
  { key: "aytam", name: "سلمى العنزي", email: "owner@aytam.demo", phone: "+966500000222", tenant: A, role: "assoc_owner", org: assoc.aytam, staff: false },
  { key: "supplier", name: "أحمد التاجر", email: "rep@sew.demo", phone: "+966500000901", tenant: A, role: "supplier_rep", org: supplier, staff: false },
  { key: "b-admin", name: "مدير تجريبي ثانٍ", email: "admin@second.demo", phone: "+966500200001", tenant: B, role: "system_admin", staff: true },
  { key: "b-spec", name: "أخصائي تجريبي ثانٍ", email: "spec@second.demo", phone: "+966500200002", tenant: B, role: "grants_specialist", staff: true },
  { key: "b-owner", name: "جمعية الطرف الثاني", email: "owner@b-assoc.demo", phone: "+966500200003", tenant: B, role: "assoc_owner", org: assoc.other, staff: false },
];

const L: string[] = [];
L.push("-- GENERATED by scripts/gen-seed.ts — do not edit. Demo data only; every name is fictional.");
L.push("begin;");
L.push(`insert into platform.donors (id, slug, name, subdomain, plan, status, is_demo) values
  (${q(A)}, 'almulhi-demo', 'مؤسسة نورة الملاحي (تجريبي)', 'almulhi', 'مؤسسي', 'active', true),
  (${q(B)}, 'second-demo', 'مؤسسة تجريبية ثانية', 'second', 'أساسي', 'onboarding', true);`);

for (const p of people) {
  const id = uuid(`person:${p.key}`);
  L.push(`insert into auth.users (id, email, phone) values (${q(id)}, ${q(p.email)}, ${q(p.phone)});`);
  L.push(`insert into iam.persons (id, full_name, email, phone) values (${q(id)}, ${q(p.name)}, ${q(p.email)}, ${q(p.phone)});`);
  L.push(`insert into iam.credentials (person_id, email, password_hash) values (${q(id)}, ${q(p.email)}, ${q(hashPassword(DEMO_PASSWORD, `salt-${p.key}`))});`);
  if (p.staff) L.push(`insert into iam.mfa (person_id, secret_enc) values (${q(id)}, ${q(DEMO_TOTP)});`);
}

const assocRows: Array<[string, string, string, string, string, string, string]> = [
  [A, assoc.albir, "1287", "جمعية البر بالدار البيضاء", "الرياض", "+966500000147", "info@albir.example.sa"],
  [A, assoc.aytam, "2210", "جمعية رعاية الأيتام بالخرج", "الخرج", "+966500000222", "info@aytam.example.sa"],
  [A, assoc.namaa, "3345", "جمعية نماء للتنمية", "الدمام", "+966500000345", "info@namaa.example.sa"],
  [B, assoc.other, "7001", "جمعية الطرف الثاني", "أبها", "+966500200003", "info@b.example.sa"],
];
for (const [t, id, lic, name, city, phone, email] of assocRows) {
  L.push(`insert into org.associations (tenant_id, id, license_no, name, city, official_phone, official_email, entity_snapshot, entity_fetched_at, registered_via, status)
  values (${q(t)}, ${q(id)}, ${q(lic)}, ${q(name)}, ${q(city)}, ${q(phone)}, ${q(email)}, ${j({ source: "seed", licenseNo: lic, name })}, now(), 'otp', 'active');`);
}
L.push(`insert into org.suppliers (tenant_id, id, name, cr_number, contact_email, billing_mode, prepaid_balance_halalas, low_balance_threshold_halalas)
  values (${q(A)}, ${q(supplier)}, 'مؤسسة الخياطة الحديثة (تجريبي)', '1010000001', 'rep@sew.demo', 'prepaid', 900000, 200000);`);

for (const p of people) {
  const pid = uuid(`person:${p.key}`);
  const manager = p.role === "grants_specialist" ? q(uuid("person:manager")) : "null";
  L.push(`insert into iam.memberships (tenant_id, id, person_id, role, org_id, manager_person_id) values (${q(p.tenant)}, ${q(uuid(`membership:${p.key}`))}, ${q(pid)}, ${q(p.role)}, ${p.org ? q(p.org) : "null"}, ${manager});`);
}

// Documents: albir and namaa ready; aytam's bank certificate expired (readiness demo, R-015).
const docs: Array<[string, string, string, string, string]> = [
  [A, assoc.albir, "license", "1287", "2027-03-01"], [A, assoc.albir, "bank_certificate", "SA-77", "2027-01-15"],
  [A, assoc.namaa, "license", "3345", "2027-06-30"], [A, assoc.namaa, "bank_certificate", "SA-88", "2027-02-01"],
  [A, assoc.aytam, "license", "2210", "2027-05-01"], [A, assoc.aytam, "bank_certificate", "SA-99", "2026-10-01"],
  [B, assoc.other, "license", "7001", "2027-01-01"], [B, assoc.other, "bank_certificate", "SA-11", "2027-01-01"],
];
for (const [t, a, type, num, exp] of docs) {
  L.push(`insert into org.documents (tenant_id, association_id, doc_type, number, expiry_date, status, confirmed_at) values (${q(t)}, ${q(a)}, ${q(type)}, ${q(num)}, ${q(exp)}, 'confirmed', now());`);
}

// Bank accounts acknowledged by finance (R-070) — IBANs are demo values, stored "encrypted" as bytes.
for (const [a, last4] of [[assoc.albir, "4471"], [assoc.namaa, "8812"], [assoc.aytam, "9920"]] as const) {
  L.push(`insert into finance.bank_accounts (tenant_id, association_id, bank_name, iban_enc, iban_last4, status, acknowledged_at) values (${q(A)}, ${q(a)}, 'مصرف الراجحي', decode('00','hex'), ${q(last4)}, 'acknowledged', now());`);
}

const v1 = uuid("version:A:2026-01"), vb = uuid("version:B:2026-01");
L.push(`insert into framework.versions (tenant_id, id, number, snapshot, snapshot_hash, reason, changes, approved_by) values
  (${q(A)}, ${q(v1)}, '2026-01', ${j(cfg)}, ${q(framework.snapshotHash(cfg))}, 'إطلاق دورة 1448', ${j(framework.diffConfigs(null, cfg))}, ${q(uuid("person:ceo"))}),
  (${q(B)}, ${q(vb)}, '2026-01', ${j(cfgB)}, ${q(framework.snapshotHash(cfgB))}, 'الإعداد الافتراضي', ${j(framework.diffConfigs(null, cfgB))}, ${q(uuid("person:b-admin"))});`);
L.push(`insert into framework.drafts (tenant_id, config, base_version_id, updated_by) values (${q(A)}, ${j(cfg)}, ${q(v1)}, ${q(uuid("person:admin"))}), (${q(B)}, ${j(cfgB)}, ${q(vb)}, ${q(uuid("person:b-admin"))});`);

const acct = uuid("account:A:grants-1448"), acctB = uuid("account:B:main");
L.push(`insert into finance.budget_accounts (tenant_id, id, name, period) values (${q(A)}, ${q(acct)}, 'منح 1448', '1448'), (${q(B)}, ${q(acctB)}, 'الميزانية العامة', '2026');`);
L.push(`insert into finance.ledger (tenant_id, account_id, kind, amount_halalas, note) values (${q(A)}, ${q(acct)}, 'allocation', 1000000000, 'ميزانية دورة 1448'), (${q(B)}, ${q(acctB)}, 'allocation', 100000000, 'ميزانية');`);

for (const [d, label] of [["2026-12-02", "اليوم الوطني (تجريبي)"], ["2027-02-22", "يوم التأسيس"]] as const) {
  L.push(`insert into kernel.holidays (tenant_id, day, label) values (${q(A)}, ${q(d)}, ${q(label)});`);
}
L.push("commit;");
writeFileSync(out, L.join("\n") + "\n");
console.log(`seed: wrote ${out}`);
export const SEED_IDS = { A, B, v1, vb, acct, assoc, supplier, uuid };
